import {
  PERMISSION_GROUPS,
  PERMISSION_LIST,
  type Permission,
} from './permissions.catalog';

/**
 * Default role matrix. Roles are seeded per-organization from this table and
 * stored as editable rows; system roles are protected. Every permission string
 * must exist in the typed catalog.
 */
export const ROLE_KEYS = [
  'SUPER_ADMIN',
  'OWNER',
  'HOSPITAL_ADMIN',
  'DOCTOR',
  'CLINICAL_OFFICER',
  'NURSE',
  'PHARMACIST',
  'LAB_TECHNICIAN',
  'RADIOLOGY_TECHNICIAN',
  'RECEPTIONIST',
  'ACCOUNTANT',
  'RECORDS_OFFICER',
  'MANAGER',
  'AUDITOR',
  'PATIENT',
] as const;

export type RoleKey = (typeof ROLE_KEYS)[number];

/** Marked roles can be updated/deleted only by a caller holding ALL permissions. */
export const SYSTEM_ROLE_KEYS: ReadonlySet<string> = new Set([
  'SUPER_ADMIN',
  'OWNER',
  'HOSPITAL_ADMIN',
]);

const G = PERMISSION_GROUPS;

const ALL = [
  G.organizations.read,
  G.organizations.manage,
  G.branches.read,
  G.branches.manage,
  G.departments.read,
  G.departments.manage,
  G.users.read,
  G.users.manage,
  G.roles.read,
  G.roles.manage,
  G.sessions.read,
  G.sessions.manage,
  G.staff.read,
  G.staff.manage,
  G.breakGlass.request,
  G.breakGlass.manage,
  G.documents.read,
  G.documents.create,
  G.documents.manage,
  G.patients.read,
  G.patients.create,
  G.patients.update,
  G.patients.manage,
  G.patients.merge,
  G.schedules.read,
  G.schedules.manage,
  G.appointments.read,
  G.appointments.create,
  G.appointments.cancel,
  G.appointments.reschedule,
  G.appointments.confirm,
  G.appointments.checkin,
  G.appointments.manage,
  G.waitlist.read,
  G.waitlist.manage,
  G.queue.read,
  G.queue.create,
  G.queue.manage,
  G.queue.prioritize,
  G.visits.read,
  G.visits.update,
  G.vitals.read,
  G.vitals.record,
  G.display.devicesManage,
  // NOTE: G.display.queueDisplay ('queue.display') is deliberately NOT part of
  // ALL. It is granted only to display-device tokens by DeviceAuthGuard.
  G.clinicalNotes.read,
  G.clinicalNotes.create,
  G.clinicalNotes.update,
  G.clinicalNotes.manage,
  G.diagnoses.read,
  G.diagnoses.create,
  G.diagnoses.update,
  G.diagnoses.manage,
  G.encounters.read,
  G.encounters.create,
  G.encounters.update,
  G.encounters.manage,
  G.followUps.read,
  G.followUps.create,
  G.followUps.update,
  G.referrals.read,
  G.referrals.create,
  G.referrals.update,
  G.tasks.read,
  G.tasks.create,
  G.tasks.update,
  G.workflows.read,
  G.workflows.manage,
  G.codings.read,
  G.codings.manage,
  G.prescriptions.read,
  G.prescriptions.create,
  G.prescriptions.update,
  G.prescriptions.cancel,
  G.prescriptions.dispense,
  G.lab.order,
  G.lab.process,
  G.lab.verify,
  G.lab.read,
  G.lab.collect,
  G.lab.release,
  G.lab.acknowledge,
  G.radiology.read,
  G.radiology.order,
  G.radiology.process,
  G.radiology.verify,
  G.radiology.release,
  G.pharmacy.dispense,
  G.pharmacy.inventory,
  G.medications.read,
  G.medications.manage,
  G.suppliers.read,
  G.suppliers.manage,
  G.purchaseOrders.read,
  G.purchaseOrders.create,
  G.purchaseOrders.approve,
  G.purchaseOrders.receive,
  G.inventory.read,
  G.inventory.manage,
  G.billing.read,
  G.billing.create,
  G.billing.manage,
  G.payments.create,
  G.payments.refund,
  G.insurance.read,
  G.insurance.manage,
  G.reports.read,
  G.audit.read,
  G.wards.read,
  G.wards.manage,
  G.beds.read,
  G.beds.manage,
  G.inpatient.read,
  G.inpatient.create,
  G.inpatient.transfer,
  G.inpatient.discharge,
  G.emergency.read,
  G.emergency.register,
  G.emergency.triage,
  G.emergency.manage,
];

/**
 * Compile-time-ish invariant: every permission referenced by a matrix role must
 * exist in the typed catalog. Guards against typos in hand-written roles.
 */
for (const p of ALL) {
  if (!(PERMISSION_LIST as readonly string[]).includes(p)) {
    throw new Error(`Role matrix references unknown permission: ${p}`);
  }
}

export interface RoleDefinition {
  key: RoleKey;
  name: string;
  description: string;
  permissions: Permission[];
}

export const DEFAULT_ROLE_MATRIX: Record<RoleKey, RoleDefinition> = {
  SUPER_ADMIN: {
    key: 'SUPER_ADMIN',
    name: 'Super Admin',
    description: 'Full platform administration of the organization.',
    permissions: [...ALL],
  },
  OWNER: {
    key: 'OWNER',
    name: 'Owner',
    description: 'Organization owner. Everything except break-glass administration.',
    permissions: ALL.filter((p) => p !== G.breakGlass.manage),
  },
  HOSPITAL_ADMIN: {
    key: 'HOSPITAL_ADMIN',
    name: 'Hospital Admin',
    description:
      'Operational administrator: staff, users, branches, departments, access.',
    permissions: [
      G.organizations.read,
      G.branches.read,
      G.branches.manage,
      G.departments.read,
      G.departments.manage,
      G.users.read,
      G.users.manage,
      G.roles.read,
      G.sessions.read,
      G.sessions.manage,
      G.staff.read,
      G.staff.manage,
      G.breakGlass.manage,
      G.documents.read,
      G.documents.create,
      G.documents.manage,
      G.patients.read,
      G.patients.create,
      G.patients.update,
      G.patients.manage,
      G.patients.merge,
      G.schedules.read,
      G.schedules.manage,
      G.appointments.read,
      G.appointments.create,
      G.appointments.cancel,
      G.appointments.reschedule,
      G.appointments.confirm,
      G.appointments.checkin,
      G.appointments.manage,
      G.waitlist.read,
      G.waitlist.manage,
      G.queue.read,
      G.visits.read,
      G.visits.update,
      G.vitals.read,
      G.encounters.read,
      G.clinicalNotes.read,
      G.diagnoses.read,
      G.followUps.read,
      G.referrals.read,
      G.tasks.read,
      G.workflows.read,
      G.workflows.manage,
      G.codings.read,
      G.prescriptions.read,
      G.medications.read,
      G.suppliers.read,
      G.purchaseOrders.read,
      G.inventory.read,
      G.billing.read,
      G.billing.manage,
      G.insurance.read,
      G.insurance.manage,
      G.lab.read,
      G.radiology.read,
      G.reports.read,
      G.audit.read,
      G.wards.read,
      G.wards.manage,
      G.beds.read,
      G.beds.manage,
      G.inpatient.read,
      G.emergency.read,
      G.emergency.manage,
    ],
  },
  DOCTOR: {
    key: 'DOCTOR',
    name: 'Doctor',
    description: 'Physician: diagnoses, prescriptions, consultations.',
    permissions: [
      G.patients.read,
      G.patients.create,
      G.patients.update,
      G.schedules.read,
      G.appointments.read,
      G.appointments.create,
      G.appointments.cancel,
      G.appointments.reschedule,
      G.appointments.confirm,
      G.appointments.checkin,
      G.clinicalNotes.read,
      G.clinicalNotes.create,
      G.clinicalNotes.update,
      G.diagnoses.read,
      G.diagnoses.create,
      G.diagnoses.update,
      G.encounters.read,
      G.encounters.create,
      G.encounters.update,
      G.followUps.read,
      G.followUps.create,
      G.followUps.update,
      G.referrals.read,
      G.referrals.create,
      G.referrals.update,
      G.tasks.read,
      G.tasks.create,
      G.tasks.update,
      G.workflows.read,
      G.codings.read,
      G.prescriptions.read,
      G.prescriptions.create,
      G.prescriptions.update,
      G.prescriptions.cancel,
      G.lab.order,
      G.lab.read,
      G.radiology.read,
      G.radiology.order,
      G.queue.read,
      G.visits.read,
      G.visits.update,
      G.vitals.read,
      G.documents.read,
      G.documents.create,
      G.reports.read,
      G.wards.read,
      G.beds.read,
      G.inpatient.read,
      G.inpatient.create,
      G.inpatient.transfer,
      G.inpatient.discharge,
      G.emergency.read,
      G.emergency.register,
      G.emergency.triage,
    ],
  },
  CLINICAL_OFFICER: {
    key: 'CLINICAL_OFFICER',
    name: 'Clinical Officer',
    description: 'Mid-level clinician: consultations and lab ordering.',
    permissions: [
      G.patients.read,
      G.patients.create,
      G.patients.update,
      G.appointments.read,
      G.appointments.create,
      G.appointments.cancel,
      G.clinicalNotes.read,
      G.clinicalNotes.create,
      G.diagnoses.read,
      G.encounters.read,
      G.followUps.read,
      G.referrals.read,
      G.tasks.read,
      G.tasks.create,
      G.tasks.update,
      G.workflows.read,
      G.codings.read,
      G.prescriptions.read,
      G.prescriptions.create,
      G.lab.order,
      G.lab.read,
      G.radiology.read,
      G.radiology.order,
      G.documents.read,
      G.documents.create,
      G.reports.read,
      G.wards.read,
      G.beds.read,
      G.inpatient.read,
      G.inpatient.create,
      G.inpatient.transfer,
      G.inpatient.discharge,
      G.emergency.read,
      G.emergency.register,
      G.emergency.triage,
    ],
  },
  NURSE: {
    key: 'NURSE',
    name: 'Nurse',
    description: 'Triage, vital signs, nursing notes.',
    permissions: [
      G.patients.read,
      G.patients.update,
      G.schedules.read,
      G.appointments.read,
      G.appointments.create,
      G.appointments.confirm,
      G.appointments.checkin,
      G.clinicalNotes.read,
      G.clinicalNotes.create,
      G.lab.order,
      G.lab.read,
      G.lab.collect,
      G.queue.read,
      G.queue.create,
      G.queue.manage,
      G.queue.prioritize,
      G.visits.read,
      G.visits.update,
      G.vitals.read,
      G.vitals.record,
      G.documents.read,
      G.documents.create,
      G.reports.read,
      G.wards.read,
      G.beds.read,
      G.inpatient.read,
      G.emergency.read,
      G.emergency.register,
    ],
  },
  PHARMACIST: {
    key: 'PHARMACIST',
    name: 'Pharmacist',
    description: 'Dispensing and pharmacy inventory.',
    permissions: [
      G.patients.read,
      G.prescriptions.read,
      G.prescriptions.dispense,
      G.pharmacy.dispense,
      G.pharmacy.inventory,
      G.medications.read,
      G.medications.manage,
      G.suppliers.read,
      G.purchaseOrders.read,
      G.inventory.read,
      G.inventory.manage,
      G.billing.read,
      G.documents.read,
      G.reports.read,
    ],
  },
  LAB_TECHNICIAN: {
    key: 'LAB_TECHNICIAN',
    name: 'Laboratory Technician',
    description: 'Processes lab orders and samples.',
    permissions: [
      G.patients.read,
      G.lab.order,
      G.lab.process,
      G.lab.read,
      G.lab.collect,
      G.lab.verify,
      G.lab.release,
      G.lab.acknowledge,
      G.referrals.read,
      G.tasks.read,
      G.tasks.update,
      G.documents.read,
      G.reports.read,
    ],
  },
  RADIOLOGY_TECHNICIAN: {
    key: 'RADIOLOGY_TECHNICIAN',
    name: 'Radiology Technician',
    description: 'Imaging orders and acquisition.',
    permissions: [
      G.patients.read,
      G.lab.order,
      G.radiology.read,
      G.radiology.order,
      G.radiology.process,
      G.radiology.verify,
      G.radiology.release,
      G.tasks.read,
      G.tasks.update,
      G.documents.read,
      G.reports.read,
    ],
  },
  RECEPTIONIST: {
    key: 'RECEPTIONIST',
    name: 'Receptionist',
    description: 'Registration, scheduling and desk cash.',
    permissions: [
      G.patients.read,
      G.patients.create,
      G.patients.update,
      G.schedules.read,
      G.appointments.read,
      G.appointments.create,
      G.appointments.cancel,
      G.appointments.reschedule,
      G.appointments.confirm,
      G.appointments.checkin,
      G.appointments.manage,
      G.waitlist.read,
      G.waitlist.manage,
      G.queue.read,
      G.queue.create,
      G.queue.manage,
      G.visits.read,
      G.visits.update,
      G.vitals.read,
      G.encounters.read,
      G.followUps.read,
      G.tasks.read,
      G.workflows.read,
      G.billing.read,
      G.billing.create,
      G.payments.create,
      G.insurance.read,
      G.documents.read,
      G.documents.create,
      G.reports.read,
      G.wards.read,
      G.beds.read,
      G.inpatient.read,
      G.emergency.read,
      G.emergency.register,
    ],
  },
  ACCOUNTANT: {
    key: 'ACCOUNTANT',
    name: 'Accountant',
    description: 'Billing, payments and refunds.',
    permissions: [
      G.patients.read,
      G.billing.read,
      G.billing.create,
      G.billing.manage,
      G.payments.create,
      G.payments.refund,
      G.insurance.read,
      G.insurance.manage,
      G.purchaseOrders.read,
      G.inventory.read,
      G.reports.read,
      G.documents.read,
      G.audit.read,
      G.inpatient.read,
      G.emergency.read,
    ],
  },
  RECORDS_OFFICER: {
    key: 'RECORDS_OFFICER',
    name: 'Records Officer',
    description: 'Medical records and demographics.',
    permissions: [
      G.patients.read,
      G.patients.create,
      G.patients.update,
      G.patients.merge,
      G.encounters.read,
      G.clinicalNotes.read,
      G.diagnoses.read,
      G.codings.read,
      G.lab.read,
      G.radiology.read,
      G.documents.read,
      G.reports.read,
      G.inpatient.read,
      G.emergency.read,
    ],
  },
  MANAGER: {
    key: 'MANAGER',
    name: 'Manager',
    description: 'Non-clinical departmental management and oversight.',
    permissions: [
      G.organizations.read,
      G.branches.read,
      G.departments.read,
      G.users.read,
      G.staff.read,
      G.patients.read,
      G.schedules.read,
      G.appointments.read,
      G.waitlist.read,
      G.queue.read,
      G.visits.read,
      G.vitals.read,
      G.encounters.read,
      G.clinicalNotes.read,
      G.diagnoses.read,
      G.followUps.read,
      G.referrals.read,
      G.tasks.read,
      G.workflows.read,
      G.codings.read,
      G.prescriptions.read,
      G.medications.read,
      G.suppliers.read,
      G.purchaseOrders.read,
      G.inventory.read,
      G.billing.read,
      G.insurance.read,
      G.lab.read,
      G.radiology.read,
      G.documents.read,
      G.reports.read,
      G.audit.read,
      G.wards.read,
      G.beds.read,
      G.inpatient.read,
      G.emergency.read,
    ],
  },
  AUDITOR: {
    key: 'AUDITOR',
    name: 'Auditor',
    description: 'Audit, clinical and reporting access (read-only).',
    permissions: [
      G.organizations.read,
      G.branches.read,
      G.departments.read,
      G.patients.read,
      G.encounters.read,
      G.clinicalNotes.read,
      G.diagnoses.read,
      G.followUps.read,
      G.referrals.read,
      G.tasks.read,
      G.workflows.read,
      G.codings.read,
      G.prescriptions.read,
      G.medications.read,
      G.suppliers.read,
      G.purchaseOrders.read,
      G.inventory.read,
      G.billing.read,
      G.insurance.read,
      G.lab.read,
      G.radiology.read,
      G.documents.read,
      G.reports.read,
      G.audit.read,
      G.wards.read,
      G.beds.read,
      G.inpatient.read,
      G.emergency.read,
    ],
  },
  PATIENT: {
    key: 'PATIENT',
    name: 'Patient',
    description:
      'Self-service access to own records (self-scoping lands with the patient module).',
    permissions: [G.patients.read, G.documents.read, G.appointments.read],
  },
};

export const DEFAULT_ROLE_LIST: readonly RoleDefinition[] = ROLE_KEYS.map(
  (key) => DEFAULT_ROLE_MATRIX[key],
);
