import { Injectable } from '@nestjs/common';
import { AuditService } from '../../database/audit.service';
import { renderPdf } from '../../jobs/pdf/pdf-renderer';
import type { PdfSection } from '../../jobs/pdf/pdf-document';
import type { RenderDocumentPdfDto } from './dto/document-job.dto';

@Injectable()
export class DocumentJobsService {
  constructor(private readonly audit: AuditService) {}

  async renderPdf(input: RenderDocumentPdfDto) {
    const sections: PdfSection[] = [];

    // A table, when one was supplied, is drawn before the free-text lines so
    // the structured part of the document is above the narrative.
    if (input.columns?.length && input.rows?.length) {
      sections.push({
        kind: 'table',
        columns: input.columns,
        rows: input.rows.map((cells) => ({ cells })),
      });
    }
    for (const line of input.lines) {
      sections.push({ kind: 'paragraph', text: line });
    }

    const pdf = await renderPdf({
      title: input.title,
      // The document kind is provenance, not a heading the reader needs, so it
      // goes in the metadata rather than competing with the title.
      subject: `${input.kind} (${input.resourceId})`,
      keywords: input.kind,
      sections,
      pageNumbers: true,
      footer: 'Generated by careOS',
    });

    const byteLength = pdf.length;
    await this.audit.record({
      action: 'pdf.rendered',
      resource: 'DocumentJob',
      resourceId: input.resourceId,
      newState: {
        kind: input.kind,
        resourceId: input.resourceId,
        byteLength,
      },
    });
    return {
      pdf,
      byteLength,
      contentType: 'application/pdf' as const,
    };
  }
}
