/**
 * Typed, versioned event catalog. Every outbox consumer subscribes to these
 * exact names. Payloads carry IDs only (never PHI). Add events here before
 * emitting them; version bumps are explicit.
 */
export const EventTypes = {
  OrganizationProvisioned: 'OrganizationProvisioned',
  OutboxEventDead: 'OutboxEventDead',
  /** Identity & access (Phase 1). */
  StaffInvited: 'Identity.StaffInvited',
  UserActivated: 'Identity.UserActivated',
  UserSuspended: 'Identity.UserSuspended',
  UserDeactivated: 'Identity.UserDeactivated',
  BreakGlassRequested: 'Access.BreakGlassRequested',
  /** Object storage (Phase 2): a document finished uploading to S3/MinIO. */
  DocumentUploaded: 'Storage.DocumentUploaded',
  /** Patients (brief Phase 2). */
  PatientRegistered: 'Patient.PatientRegistered',
  PatientUpdated: 'Patient.PatientUpdated',
  PatientDuplicateConfirmed: 'Patient.PatientDuplicateConfirmed',
  PatientMerged: 'Patient.PatientMerged',
  PatientGuardianAdded: 'Patient.PatientGuardianAdded',
  PatientGuardianRemoved: 'Patient.PatientGuardianRemoved',
  PatientConsentChanged: 'Patient.PatientConsentChanged',
  PatientAllergyRecorded: 'Patient.PatientAllergyRecorded',
  PatientMedicalHistoryAdded: 'Patient.PatientMedicalHistoryAdded',
  /** Scheduling & patient flow (brief Phase 3). Payloads carry IDs only. */
  AppointmentBooked: 'Scheduling.AppointmentBooked',
  AppointmentConfirmed: 'Scheduling.AppointmentConfirmed',
  AppointmentCheckedIn: 'Scheduling.AppointmentCheckedIn',
  AppointmentStarted: 'Scheduling.AppointmentStarted',
  AppointmentCompleted: 'Scheduling.AppointmentCompleted',
  AppointmentCancelled: 'Scheduling.AppointmentCancelled',
  AppointmentNoShow: 'Scheduling.AppointmentNoShow',
  AppointmentRescheduled: 'Scheduling.AppointmentRescheduled',
  WaitlistJoined: 'Scheduling.WaitlistJoined',
  WaitlistOfferCreated: 'Scheduling.WaitlistOfferCreated',
  WaitlistOfferAccepted: 'Scheduling.WaitlistOfferAccepted',
  WaitlistOfferDeclined: 'Scheduling.WaitlistOfferDeclined',
  QueueEntryCreated: 'Queue.EntryCreated',
  QueueEntryCalled: 'Queue.EntryCalled',
  QueueEntryStarted: 'Queue.EntryStarted',
  QueueEntryCompleted: 'Queue.EntryCompleted',
  QueueEntryNoShow: 'Queue.EntryNoShow',
  QueueEntryTransferred: 'Queue.EntryTransferred',
  QueueEntryPriorityChanged: 'Queue.EntryPriorityChanged',
  VisitStatusChanged: 'Queue.VisitStatusChanged',
  VitalRecorded: 'Triage.VitalRecorded',
  DisplayDevicePaired: 'Display.DevicePaired',
  DisplayDeviceRevoked: 'Display.DeviceRevoked',
  DisplayDeviceRotated: 'Display.DeviceRotated',
  /** Clinical core (brief Phase 4). Payloads carry IDs only. */
  EncounterCreated: 'Clinical.EncounterCreated',
  EncounterStarted: 'Clinical.EncounterStarted',
  EncounterCompleted: 'Clinical.EncounterCompleted',
  ClinicalNoteCreated: 'Clinical.NoteCreated',
  ClinicalNoteFinalized: 'Clinical.NoteFinalized',
  ClinicalNoteAmended: 'Clinical.NoteAmended',
  DiagnosisRecorded: 'Clinical.DiagnosisRecorded',
  DiagnosisUpdated: 'Clinical.DiagnosisUpdated',
  DiagnosisResolved: 'Clinical.DiagnosisResolved',
  FollowUpCreated: 'Clinical.FollowUpCreated',
  FollowUpStatusChanged: 'Clinical.FollowUpStatusChanged',
  ReferralCreated: 'Clinical.ReferralCreated',
  ReferralAccepted: 'Clinical.ReferralAccepted',
  ReferralRejected: 'Clinical.ReferralRejected',
  ReferralCompleted: 'Clinical.ReferralCompleted',
  ReferralCancelled: 'Clinical.ReferralCancelled',
  TaskCreated: 'Clinical.TaskCreated',
  TaskStatusChanged: 'Clinical.TaskStatusChanged',
  CodingSystemImported: 'Reference.CodingSystemImported',
  WorkflowTransitionAdded: 'Clinical.WorkflowTransitionAdded',
  /** Inventory & pharmacy (brief Phase 5). Payloads carry IDs only. */
  PrescriptionIssued: 'Pharmacy.PrescriptionIssued',
  PrescriptionDispensed: 'Pharmacy.PrescriptionDispensed',
  PrescriptionCancelled: 'Pharmacy.PrescriptionCancelled',
  StockReceived: 'Pharmacy.StockReceived',
  StockAdjusted: 'Pharmacy.StockAdjusted',
  StockTransferReceived: 'Pharmacy.StockTransferReceived',
  PurchaseOrderReceived: 'Pharmacy.PurchaseOrderReceived',
  /** Billing & invoicing (brief Phase 7). Payloads carry IDs only. */
  InvoiceIssued: 'Billing.InvoiceIssued',
  InvoiceCancelled: 'Billing.InvoiceCancelled',
  InvoiceRefunded: 'Billing.InvoiceRefunded',
  PaymentCompleted: 'Billing.PaymentCompleted',
  PaymentRefunded: 'Billing.PaymentRefunded',
  ClaimSubmitted: 'Billing.ClaimSubmitted',
  ClaimDecided: 'Billing.ClaimDecided',
  ClaimPaid: 'Billing.ClaimPaid',
  /** Laboratory & radiology (brief Phase 6). Payloads carry IDs only. */
  LabOrderCreated: 'Lab.OrderCreated',
  LabSampleCollected: 'Lab.SampleCollected',
  LabSampleRejected: 'Lab.SampleRejected',
  LabResultEntered: 'Lab.ResultEntered',
  LabResultAmended: 'Lab.ResultAmended',
  LabResultVerified: 'Lab.ResultVerified',
  LabResultReleased: 'Lab.ResultReleased',
  LabCriticalResultRaised: 'Lab.CriticalResultRaised',
  LabCriticalResultAcknowledged: 'Lab.CriticalResultAcknowledged',
  RadiologyOrderCreated: 'Radiology.OrderCreated',
  RadiologyPerformed: 'Radiology.Performed',
  RadiologyReportSubmitted: 'Radiology.ReportSubmitted',
  RadiologyReportReleased: 'Radiology.ReportReleased',
  /** Inpatient & emergency (brief Phase 8). Payloads carry IDs only. */
  AdmissionCreated: 'Inpatient.AdmissionCreated',
  AdmissionTransferred: 'Inpatient.AdmissionTransferred',
  AdmissionDischarged: 'Inpatient.AdmissionDischarged',
  BedStatusChanged: 'Inpatient.BedStatusChanged',
  EmergencyVisitRegistered: 'Emergency.VisitRegistered',
  EmergencyVisitTriaged: 'Emergency.VisitTriaged',
  EmergencyPriorityRecorded: 'Emergency.PriorityRecorded',
  EmergencyVisitAssessed: 'Emergency.VisitAssessed',
  EmergencyVisitTreatmentStarted: 'Emergency.VisitTreatmentStarted',
  EmergencyVisitObserved: 'Emergency.VisitObserved',
  EmergencyVisitAdmitted: 'Emergency.VisitAdmitted',
  EmergencyVisitReferred: 'Emergency.VisitReferred',
  EmergencyVisitDischarged: 'Emergency.VisitDischarged',
  /**
   * Test/demo signal used by the Phase 0 harness (see modules/demo and
   * docs/limitations.md). Removed from the catalog before production use.
   */
  Probe: 'CareOS.Probe',
} as const;

export type EventType = (typeof EventTypes)[keyof typeof EventTypes];

export const EVENT_VERSION: Record<EventType, number> = {
  [EventTypes.OrganizationProvisioned]: 1,
  [EventTypes.OutboxEventDead]: 1,
  [EventTypes.StaffInvited]: 1,
  [EventTypes.UserActivated]: 1,
  [EventTypes.UserSuspended]: 1,
  [EventTypes.UserDeactivated]: 1,
  [EventTypes.BreakGlassRequested]: 1,
  [EventTypes.DocumentUploaded]: 1,
  [EventTypes.PatientRegistered]: 1,
  [EventTypes.PatientUpdated]: 1,
  [EventTypes.PatientDuplicateConfirmed]: 1,
  [EventTypes.PatientMerged]: 1,
  [EventTypes.PatientGuardianAdded]: 1,
  [EventTypes.PatientGuardianRemoved]: 1,
  [EventTypes.PatientConsentChanged]: 1,
  [EventTypes.PatientAllergyRecorded]: 1,
  [EventTypes.PatientMedicalHistoryAdded]: 1,
  [EventTypes.AppointmentBooked]: 1,
  [EventTypes.AppointmentConfirmed]: 1,
  [EventTypes.AppointmentCheckedIn]: 1,
  [EventTypes.AppointmentStarted]: 1,
  [EventTypes.AppointmentCompleted]: 1,
  [EventTypes.AppointmentCancelled]: 1,
  [EventTypes.AppointmentNoShow]: 1,
  [EventTypes.AppointmentRescheduled]: 1,
  [EventTypes.WaitlistJoined]: 1,
  [EventTypes.WaitlistOfferCreated]: 1,
  [EventTypes.WaitlistOfferAccepted]: 1,
  [EventTypes.WaitlistOfferDeclined]: 1,
  [EventTypes.QueueEntryCreated]: 1,
  [EventTypes.QueueEntryCalled]: 1,
  [EventTypes.QueueEntryStarted]: 1,
  [EventTypes.QueueEntryCompleted]: 1,
  [EventTypes.QueueEntryNoShow]: 1,
  [EventTypes.QueueEntryTransferred]: 1,
  [EventTypes.QueueEntryPriorityChanged]: 1,
  [EventTypes.VisitStatusChanged]: 1,
  [EventTypes.VitalRecorded]: 1,
  [EventTypes.DisplayDevicePaired]: 1,
  [EventTypes.DisplayDeviceRevoked]: 1,
  [EventTypes.DisplayDeviceRotated]: 1,
  [EventTypes.EncounterCreated]: 1,
  [EventTypes.EncounterStarted]: 1,
  [EventTypes.EncounterCompleted]: 1,
  [EventTypes.ClinicalNoteCreated]: 1,
  [EventTypes.ClinicalNoteFinalized]: 1,
  [EventTypes.ClinicalNoteAmended]: 1,
  [EventTypes.DiagnosisRecorded]: 1,
  [EventTypes.DiagnosisUpdated]: 1,
  [EventTypes.DiagnosisResolved]: 1,
  [EventTypes.FollowUpCreated]: 1,
  [EventTypes.FollowUpStatusChanged]: 1,
  [EventTypes.ReferralCreated]: 1,
  [EventTypes.ReferralAccepted]: 1,
  [EventTypes.ReferralRejected]: 1,
  [EventTypes.ReferralCompleted]: 1,
  [EventTypes.ReferralCancelled]: 1,
  [EventTypes.TaskCreated]: 1,
  [EventTypes.TaskStatusChanged]: 1,
  [EventTypes.CodingSystemImported]: 1,
  [EventTypes.WorkflowTransitionAdded]: 1,
  [EventTypes.PrescriptionIssued]: 1,
  [EventTypes.PrescriptionDispensed]: 1,
  [EventTypes.PrescriptionCancelled]: 1,
  [EventTypes.StockReceived]: 1,
  [EventTypes.StockAdjusted]: 1,
  [EventTypes.StockTransferReceived]: 1,
  [EventTypes.PurchaseOrderReceived]: 1,
  [EventTypes.InvoiceIssued]: 1,
  [EventTypes.InvoiceCancelled]: 1,
  [EventTypes.InvoiceRefunded]: 1,
  [EventTypes.PaymentCompleted]: 1,
  [EventTypes.PaymentRefunded]: 1,
  [EventTypes.ClaimSubmitted]: 1,
  [EventTypes.ClaimDecided]: 1,
  [EventTypes.ClaimPaid]: 1,
  [EventTypes.LabOrderCreated]: 1,
  [EventTypes.LabSampleCollected]: 1,
  [EventTypes.LabSampleRejected]: 1,
  [EventTypes.LabResultEntered]: 1,
  [EventTypes.LabResultAmended]: 1,
  [EventTypes.LabResultVerified]: 1,
  [EventTypes.LabResultReleased]: 1,
  [EventTypes.LabCriticalResultRaised]: 1,
  [EventTypes.LabCriticalResultAcknowledged]: 1,
  [EventTypes.RadiologyOrderCreated]: 1,
  [EventTypes.RadiologyPerformed]: 1,
  [EventTypes.RadiologyReportSubmitted]: 1,
  [EventTypes.RadiologyReportReleased]: 1,
  [EventTypes.AdmissionCreated]: 1,
  [EventTypes.AdmissionTransferred]: 1,
  [EventTypes.AdmissionDischarged]: 1,
  [EventTypes.BedStatusChanged]: 1,
  [EventTypes.EmergencyVisitRegistered]: 1,
  [EventTypes.EmergencyVisitTriaged]: 1,
  [EventTypes.EmergencyPriorityRecorded]: 1,
  [EventTypes.EmergencyVisitAssessed]: 1,
  [EventTypes.EmergencyVisitTreatmentStarted]: 1,
  [EventTypes.EmergencyVisitObserved]: 1,
  [EventTypes.EmergencyVisitAdmitted]: 1,
  [EventTypes.EmergencyVisitReferred]: 1,
  [EventTypes.EmergencyVisitDischarged]: 1,
  [EventTypes.Probe]: 1,
};
