import createClient from 'openapi-fetch';

import { publicEnv } from '@/lib/env';

import type { paths } from './schema';

/**
 * Typed API client.
 *
 * Two deliberate constraints:
 *
 *  1. The base URL is a *path*, not an origin. Requests go to our own origin and
 *     the Next server proxies them to API_INTERNAL_URL, so the API host is never
 *     exposed to the browser, no CORS preflight is needed, and cookies stay
 *     first-party. See docs/decisions.md ADR-004.
 *  2. Credentials are included. The session cookie is HttpOnly and SameSite, so
 *     the browser attaches it automatically and JS can never read it.
 *
 * The `paths` type comes from `schema.d.ts`, generated by `npm run api:types`
 * from `openapi/careos.partial.json`. A handler that drifts from the contract is
 * therefore a type error rather than a runtime surprise.
 */
export const api = createClient<paths>({
  baseUrl: publicEnv.apiBasePath,
  credentials: 'same-origin',
  headers: {
    Accept: 'application/json',
    'Content-Type': 'application/json',
  },
});

export type ApiPaths = paths;
