/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/public/config': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Platform configuration for the unauthenticated surface. */
    get: operations['getPublicConfig'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/public/facilities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Published facilities. Unauthenticated; only fields marked public are returned. */
    get: operations['listPublicFacilities'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/public/emergency-requests': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit an emergency intake request.
     * @description Rate limited. The caller receives a reference to track with, not a clinical assessment. The UI must not present a response as triage.
     */
    post: operations['submitEmergencyRequest'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current session identity and role grants. */
    get: operations['getCurrentUser'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Meta: {
      requestId: string;
      /** Format: date-time */
      timestamp?: string;
    };
    SuccessEnvelope: {
      /** @constant */
      success: true;
      data: unknown;
      meta?: components['schemas']['Meta'];
    };
    ApiErrorBody: {
      /**
       * @description Stable machine code. The UI maps this through src/lib/errors/catalog.ts and never renders `message` directly.
       * @enum {string}
       */
      code:
        | 'VALIDATION_ERROR'
        | 'UNAUTHENTICATED'
        | 'FORBIDDEN'
        | 'NOT_FOUND'
        | 'CONFLICT'
        | 'UNPROCESSABLE_ENTITY'
        | 'RATE_LIMITED'
        | 'INTERNAL_ERROR'
        | 'SERVICE_UNAVAILABLE';
      /** @description Diagnostic detail. Not for display. */
      message: string;
      details?: Record<string, never>[];
    };
    ErrorEnvelope: {
      /** @constant */
      success: false;
      error: components['schemas']['ApiErrorBody'];
      meta?: components['schemas']['Meta'];
    };
    /** @enum {string} */
    FacilityType: 'GENERAL' | 'REFERRAL' | 'SPECIALIST' | 'CLINIC' | 'PRIMARY_CARE';
    PublicConfig: {
      platformName: string;
      defaultLocale: string;
      supportedLocales: string[];
      features?: {
        emergencyIntake?: boolean;
        displayScreens?: boolean;
        patientPortal?: boolean;
      };
    };
    /** @description Only publishable fields. Internal notes, staffing and billing data must never appear here. */
    PublicFacility: {
      id: string;
      name: string;
      shortName?: string | null;
      type: components['schemas']['FacilityType'];
      /** @enum {string} */
      status: 'ACTIVE' | 'INACTIVE';
      phone?: string | null;
      emergencyPhone?: string | null;
      address?: string | null;
    };
    EmergencyRequestInput: {
      facilityId: string;
      patientName: string;
      phone: string;
      description: string;
      /** @constant */
      consentToContact: true;
    };
    /** @description A tracking receipt. Deliberately carries no clinical assessment: intake must not imply triage. */
    EmergencyRequestReceipt: {
      id: string;
      reference: string;
      status: string;
      /** Format: date-time */
      createdAt: string;
    };
    RoleGrant: {
      role: string;
      facilityId?: string | null;
      facilityName?: string | null;
      scope: string;
    };
    BreakGlassGrant: {
      facilityId?: string | null;
      /** Format: date-time */
      grantedAt: string;
      /** Format: date-time */
      expiresAt?: string | null;
      reason?: string | null;
    };
    CurrentUser: {
      id: string;
      /** Format: email */
      email: string;
      displayName?: string | null;
      /** @description The API returns the user twice: a top-level identity for the session, and a nested `user` object carrying `roles` as grant objects. Both shapes are asserted against the backend in Phase 12; see docs/api-contract-gaps.md GAP-004. */
      user: {
        id: string;
        /** Format: email */
        email: string;
        displayName?: string | null;
        roles: components['schemas']['RoleGrant'][];
      };
      /** @description Legacy flat string list, retained additively for compatibility. Prefer `user.roles`. */
      roles: string[];
      /** @description Legacy single break-glass object, retained additively. Prefer `breakGlassGrants`. */
      breakGlass?: {
        [key: string]: unknown;
      } | null;
      breakGlassGrants?: components['schemas']['BreakGlassGrant'][];
    };
  };
  responses: {
    /** @description Request failed validation */
    ValidationError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description No valid session */
    Unauthenticated: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description Too many requests */
    RateLimited: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description Upstream dependency unavailable */
    ServiceUnavailable: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description Unexpected server error */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getPublicConfig: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Configuration */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SuccessEnvelope'] & {
            data?: components['schemas']['PublicConfig'];
          };
        };
      };
    };
  };
  listPublicFacilities: {
    parameters: {
      query?: {
        /** @description Free-text search over name and address. */
        q?: string;
        type?: components['schemas']['FacilityType'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Matching facilities */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SuccessEnvelope'] & {
            data?: {
              items: components['schemas']['PublicFacility'][];
              total: number;
            };
          };
        };
      };
      500: components['responses']['InternalError'];
    };
  };
  submitEmergencyRequest: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EmergencyRequestInput'];
      };
    };
    responses: {
      /** @description Request accepted */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SuccessEnvelope'] & {
            data?: components['schemas']['EmergencyRequestReceipt'];
          };
        };
      };
      400: components['responses']['ValidationError'];
      429: components['responses']['RateLimited'];
      503: components['responses']['ServiceUnavailable'];
    };
  };
  getCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SuccessEnvelope'] & {
            data?: components['schemas']['CurrentUser'];
          };
        };
      };
      401: components['responses']['Unauthenticated'];
    };
  };
}
